
name: cipr
channels:
  - defaults
  - plotly
dependencies:
  - python
  - pandas      # numpy included in this
  - matplotlib
  - scipy
  - ipykernel   # optional for vscode
  - plotly
  - ipywidgets
  - nbformat

